### ISSUE TITLE
Dependency not found after install

### ISSUE THREAD

**Issue by scottsandersdev** [Esvalirion/vue-drag-it-dude#7]
Having a strange issue after installing this module. Even though I see it in my node-modules, package.json, and even see it listed in the vue ui "project dependencies" window, I still get the following error when attempting to import it - 
```
This dependency was not found:

* vue-drag-it-dude in ./src/main.js

To install it, you can run: npm install --save vue-drag-it-dude
```

Any ideas what I may be missing?

**Comment by Esvalirion** [comment]
Can you show component import?
It must be like 
`import component from './DragItDude.vue';`

**Comment by karambafe** [comment]
Oops, this is my mistake :)
@Esvalirion i fixed this in [PR8](https://github.com/Esvalirion/vue-drag-it-dude/pull/8)

@scottsandersdev and you can use this option:
```
import DragItDude from 'vue-drag-it-dude/dist/vue-drag-it-dude.esm';
```

**Comment by dev7ch** [comment]
Nuxt implementation

```

In your component or page template

<no-ssr>
<drag-it-dude class="stage-settings" id="canvas-settings"
  @activated="handleActivated"
  @dragging="handleDragging"
   @dropped="handleDropped" >
// ... your draggable content
</drag-it-dude>
</no-ssr>
```
in `plugins/drag.js

```
import Vue from 'vue'
import DragItDude from 'vue-drag-it-dude/dist/vue-drag-it-dude.umd.js'

Vue.component('vue-drag-it-dude', DragItDude)
```

include it with `ssr:false` in your nuxt config section

**Comment by karambafe** [comment]
@dev7ch thanks!

I add this information in [PR9](https://github.com/Esvalirion/vue-drag-it-dude/pull/9)
